# Generated by Django 2.1.2 on 2018-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=2)),
                ('due_date', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('expired', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['priority', 'due_date', 'title'],
            },
        ),
    ]
